const menu = [
  {
    id: 1,
    title: 'fried plantain and eggs',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'eba and vegetable soup',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'moin moin with leaf',
    category: 'dinner',
    price: 6.99,
    img: './images/item-7.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'bread and tea',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-5.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egussi and pounded yam',
    category: 'lunch',
    price: 22.99,
    img: './images/item-6.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'ofada rice',
    category: 'dinner',
    price: 18.99,
    img: './images/item-4.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'akara and pap',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-3.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'fufu and okraw soup',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'beans portage',
    category: 'dinner',
    price: 16.99,
    img: './images/item-9.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'fried yam with egg source and tea',
    category: 'breakfast',
    price: 12.99,
    img: './images/item-10.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 11,
    title: 'jellof rice',
    category: 'lunch',
    price: 16.99,
    img: './images/item-11.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'mede mede',
    category: 'dinner',
    price: 16.99,
    img: './images/item-12.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'moin moin',
    category: 'breakfast',
    price: 12.99,
    img: './images/item-13.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 14,
    title: 'white rice',
    category: 'lunch',
    price: 16.99,
    img: './images/item-14.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: 'rice and beans with source',
    category: 'dinner',
    price: 16.99,
    img: './images/item-15.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
